services:
  - type: web
    name: real-estate-api
    runtime: node
    rootDir: backend
    plan: free

    buildCommand: npm install
    startCommand: npm start

    envVars:
      - key: NODE_ENV
        value: production

      - key: JWT_SECRET
        generateValue: true

      - key: MONGODB_URI
        sync: false

      - key: APP_URL
        sync: false

      - key: EMAIL_USER
        sync: false

      - key: EMAIL_APP_PASSWORD
        sync: false

  - type: web
    name: dreamhome-frontend
    runtime: static
    rootDir: frontend
    buildCommand: ""
    staticPublishPath: .